
services:
  web:
    build:
      context: ./discord
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./discord:/app
    environment:
      - PYTHONUNBUFFERED=1